### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by mateka** [BSData/argatoria#1]
### Reference contact

codedoneright-eu

### Your Discord

mad

### Additional information

I would like to help with updating Argatoria's data files.

**Comment by codedoneright-eu** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/5077347274)
:robot: Invited @mateka with **push** access. Invite can be accepted on https://github.com/BSData/argatoria/invitations
